kind: pipeline
type: docker
name: build-versioned-image

trigger:
  branch:
    - '3.13'
  event:
    - pull_request

# Build the docker image for amd64 architecture
steps:
  - name: version-docker-image-build
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      platforms:
        - linux/amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/python
      tags:
        - latest
        - 3.13.7
        - 3.13.7-drone-build-${DRONE_BUILD_NUMBER}

  # Slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts

---

kind: pipeline
type: docker
name: test-main-image

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: main-docker-image-test
    image: kernel528/python:latest
    when:
      branch:
        - main
      when:
        - push
    commands:
      - cat /etc/alpine-release
      - "python --version"

  # Slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts

---
kind: pipeline
type: docker
name: build-tagged-image

trigger:
  event:
    - tag

# Build the docker image for the tagged release
steps:
  - name: tag-docker-image-build
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/python
      tags:
        - ${DRONE_TAG}

  # Slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts