pipeline:
  docker-python3:
    when:
      branch: 3.8
      event: push
    image: plugins/docker
    repo: kernel528/python
    secrets: [ docker_username, docker_password ]
    dockerfile: Dockerfile
    tag:
      - latest
      - 3.8.6
      - 3.8.6-${DRONE_COMMIT:0:8}-drone-build-${DRONE_BUILD_NUMBER}

  # Post notification to slack channel
  slack:
    when:
      status:
        - success
        - failure
      event:
        - push
        - tag
    image: plugins/slack
    channel: orpheus-alerts
    webhook: https://hooks.slack.com/services/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
    template: >
      Drone build {{uppercase build.status}} for {{ build.link }} with git commit {{ truncate build.commit 8 }} to git branch ({{ build.branch }}) by {{ build.author }}.
