kind: pipeline
type: docker
name: python-image-build

# Trigger conditions
trigger:
  branch:
    - '3.13'
    - main
  event:
    - custom
    - push
    - pull_request

# Pipeline steps
steps:

  # Build image
  - name: docker-build
    image: plugins/docker
    when:
      branch:
        - '3.13'
      when:
        - push
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/python
      tags:
        - latest
        - 3.13.0
        - 3.13.0-${DRONE_COMMIT:0:8}-drone-build-${DRONE_BUILD_NUMBER}

  # Test image
  - name: docker-test
    image: kernel528/python:latest
    when:
      branch:
        - main
      when:
        - push
    commands:
      - cat /etc/alpine-release
      - "python --version"

  # Slack notification
  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts
    when:
      status:
        - failure
        - success